### ISSUE TITLE
where i got confuse

### ISSUE THREAD

**Issue by luyifanlu** [GMvandeVen/brain-inspired-replay#1]
https://github.com/GMvandeVen/brain-inspired-replay/blob/ae102358855c9b0512fcf7851c12c5354ef2ab1f/models/vae.py#L761
i don"t understand why how can use like that ,there are  no function infer.

**Comment by GMvandeVen** [comment]
This is indeed confusing, you could read this as `self.forward(...)`. It has to do with the way PyTorch's forward function works, maybe this is useful: https://discuss.pytorch.org/t/any-different-between-model-input-and-model-forward-input/3690
