### ISSUE TITLE
command to run baselines

### ISSUE THREAD

**Issue by puneater** [GMvandeVen/brain-inspired-replay#10]
Hi, I am really amazed by the number of options that are being provided in the code to run the experiments. I was wondering how to run the baselines, that is, Joint Training and None [simple sequential learning], as mentioned in the article. What is the code and the parameters to run these baseline algorithms seperately, like we can run algorithms like GR, LWF, etc?

**Comment by GMvandeVen** [comment]
Hi, I'm sorry for the late reply, your message got buried somewhere.
To run the baselines you mention, you can use the following code:
- Joint training: `./main_cl.py --replay=offline`
- None (simple sequential learnign): `./main_cl.py --replay=none`

Note that you can also leave out `--replay=none`, as this is the default.

**Comment by puneater** [comment]
Hey,

Thank you for the reply.

I went through the compare_[dataset].py files and figured out the parameters for none and joint baselines. 
Just wanted to make sure that these were the only parameters which are passed in the command line.

Once again, thank you very much @GMvandeVen .
