### ISSUE TITLE
What is the role of replay_mode='current' here

### ISSUE THREAD

**Issue by JiahaoChow** [GMvandeVen/brain-inspired-replay#12]
It seems that using this option makes x_the same as x in train_a_batch. Why should we replay the current data?

**Comment by GMvandeVen** [comment]
Thanks for your question! It's indeed correct that the option `--replay_mode='current'` makes that the current data is replayed. It's perhaps a bit unintuitive, but this is essentially what the method Learning without Forgetting does (https://arxiv.org/abs/1606.09282). Hope that helps!

**Comment by JiahaoChow** [comment]
Thank you very much! Looking forward to your future work!
