### ISSUE TITLE
How to reload model and predict?

### ISSUE THREAD

**Issue by pardont** [GMvandeVen/brain-inspired-replay#4]
Hi GMvandeVen,  the model will be saved after run 
./main_cl.py --experiment=splitMNIST --scenario=class --replay=generative --brain-inspired --pdf

is there any command to load trained model and use the model to predict?

**Comment by GMvandeVen** [comment]
Hi, you can use the option `--test` to load a previously trained model and evaluate its performance.

If you initially used this command to train the model:
`./main_cl.py --experiment=splitMNIST --scenario=class --replay=generative --brain-inspired --pdf`

Then you can use the following command to load that model and test it:
`./main_cl.py --experiment=splitMNIST --scenario=class --replay=generative --brain-inspired --pdf --test`

**Comment by pardont** [comment]
works great, thanks.
