### ISSUE TITLE
result for 'scenario = class'

### ISSUE THREAD

**Issue by leatherking** [GMvandeVen/brain-inspired-replay#6]
Hi, I am learning on your codes for a week and I have run several experiments so far. I have some questions.

1. The setting of 'scenario='task'' works well, but the other one of 'scenario=class' is what I am confused with : 
 For example, if I set a setting: 'expri..=splitMNIST, tasks=5, scenario=class ' , the result is "-task1: xx. xx   -task2: xx. xx   task3: xx. xx  -task4: xx. xx    -task5: xx. xx". I don't understand what it means as the result format is the same with 'scenario=task'. Does the classifier uses  single-head or multi-head for class-IL ?

2. In my experiments, EWC, SI, LwF had no effect on class-IL , all forgot. Is it normal?

Best regard

**Comment by GMvandeVen** [comment]
1.)	The use of the term ‘task’ in the class-incremental learning scenario is indeed confusing; the term ‘episode’ would be more appropriate.
The results that are printed to the screen at the end of training are indeed for the Class-IL scenario (i.e., using a single-head classifier). For example, the reported accuracy for “task 1” is the average accuracy of the final model for the test data from task 1 (e.g., all the test samples that are ‘0’s and ‘1’s for split-MNIST), but whereby the model had to choose between all possible classes (e.g., a 10-way classification for split-MNIST).

2.)	Yes, that EWC, SI and LwF have almost no effect when they are trained and evaluated according the Class-IL scenario is indeed what I would expect. That’s what I found as well.

Hope this helps!

**Comment by leatherking** [comment]
Many thanks for you! It helps a lot！
