### ISSUE TITLE
Can't run cmopare_permMNIST100_bir.py

### ISSUE THREAD

**Issue by AIwuya** [GMvandeVen/brain-inspired-replay#8]
Hi,
When I  ran compare_permMNIST100_bir.py,  and set --seed=12 --n-seeds=5.
Then an error occureed, 

File "/media/wuya/DATA/Code/continual_learning/brain-inspired-replay/options.py", line 350, in set_defaults
    args.xdg_prop = 0. if args.scenario=="task" and args.xdg_prop is None else args.xdg_prop
AttributeError: 'Namespace' object has no attribute 'xdg_prop'

I don't know where to set xdg_prop, can you tell me how to do it?
Thank you very much!

![Screenshot from 2021-02-03 00-23-12](https://user-images.githubusercontent.com/26964384/106675810-14a8eb80-65b6-11eb-9919-53434b281804.png)

**Comment by GMvandeVen** [comment]
Hi, thanks for your feedback!
This was indeed a mistake in the code, my apologies. I should have defined `args.xdg_prop` somewhere in that script. I have just fixed it (by adding this line: https://github.com/GMvandeVen/brain-inspired-replay/blob/f9e433134200b11d8c59ecb1c35ab5ba3042c691/compare_permMNIST100_bir.py#L29, in case you’re interested). In `compare_CIFAR100_bir.py` there was actually a similar mistake that is now fixed as well. Sorry about that!
Please let me know if you encounter other errors, this is very useful feedback.

**Comment by AIwuya** [comment]
Hi, thank you for your timely modification!
Now, they are working~
